version: "3.8"
services:
  web:
    build:
      context: ../website
      dockerfile: DevDockerfile
    ports: 
      - "3000:3000"
    stdin_open: true
  service:
    build:
      context: ../service
      dockerfile: DevDockerfile
    ports:
      - "4000:4000"
    env_file: .env
    links:
      - clearlydefined_mongo_db
#  crawler:
#    build: ../crawler
#    env_file: .env
#    ports:
#      - "5000:5000"
  clearlydefined_mongo_db:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  clearlydefined_mongo_seed:
    build:
      context: ./mongo_seed 
    links:
      - clearlydefined_mongo_db
