version: "3.8"
services:
  web:
    build:
      context: ../website
      dockerfile: DevDockerfile
    ports: 
      - "3000:3000"
    env_file: .env
    stdin_open: true
  service:
    build:
      context: ../service
      dockerfile: DevDockerfile
    env_file: .env
    ports:
      - "4000:4000"
    env_file: .env
#  crawler:
#    build: ../crawler
#    env_file: .env
#    ports:
#      - "5000:5000"
  curations_mongo_db:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=curations-dev-docker
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
#  definitions_mongo_db:
#    image: "mongo:latest"
#    ports:
#      - "27018:27018"
#    environment:
#      - MONGO_INITDB_DATABASE=definitions-dev-docker
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=secret


